<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
   <title>Aol Sites</title>
   <link rel="stylesheet" href="http://yui.yahooapis.com/2.8.0r4/build/reset-fonts-grids/reset-fonts-grids.css" type="text/css">
   <link rel="stylesheet" href="http://hatch.aol.com/social/css/aolit_lp.css" type="text/css">
   <link href="http://o.aolcdn.com/os/autos/global/favicon.ico" rel="shortcut icon">  
</head>
<body>
<div id="doc3" class="yui-t7">
   <div id="hd"><h1>Aol.it Sites</h1></div>
   <div id="bd">
	<div id="list"class="yui-g">
<p>We think we got everything, but just to be sure here's a list of every AOL site that is included in the contest:</p>
<pre>
africana.com 
aisledash.com 
alice.aol.de 
aol.ca 
aol.co.jp 
aol.co.uk 
aol.com 
aol.com.hk 
aol.com.pr 
aol.cricket20.com 
aol.de 
aol.fr 
aol.jp 
aol.qc.ca 
aolbollywood.com 
aolbroadband.welcomescreen.aol.co.uk 
aolcommunity.aol.co.jp 
aolhealth.com 
aollatinoblog.com 
aolmobile.aol.com 
aolnews.com 
aolracing.com 
aolradioblog.com 
aolsvc.latino.stats.aol.com 
aolsvc.mercurytivo.aol.com 
aolsvc.news.aol.com 
aolsvc.pf.aol.com 
aolsvc.travel.survey.aol.com 
aolsvc.weather.aol.com 
aoltv.ca 
aoltv.co.uk 
aoltvlistings.compuserve.com 
aoltvlistings.cssvc.com 
aoltvlistings.netscape.com 
aolvideoblog.com 
archive.blackvoices.com 
argentina.aol.com 
asylum.co.uk 
asylum.com 
asylum.com.au 
asylum.in 
asylum.jp 
asylumitalia.it 
auto-insurance.blackvoices.com 
autoblog.com 
automoviles.aol.com 
autos.aol.com 
autos.blackvoices.com 
backporch.fanhouse.com 
beta.gamedaily.com 
blackvoices.aol.com 
blackvoices.com 
blog.emurse.com 
blog.games.com 
blog.propeller.com 
blog.winamp.com 
bloggingbuyouts.com 
bloggingneworleans.com 
bloggingstocks.com 
bloggingsundance.com 
blogs.blackvoices.com 
bollywoodblog.aol.in 
books.aol.com 
boxing.fanhouse.com 
broadband.aol.co.uk 
buenos-padres.com 
buscadorlatino.aol.com 
bvblackspin.com 
bvbuzz.com 
bvhairtalk.com 
bvnewswire.com 
bvonbooks.com 
bvonlove.com 
bvonmoney.com 
bvonmovies.com 
bvonsports.com 
bvonstyle.com 
bvwellness.com 
cambio.com 
canada.aol.com 
careerhelp.emurse.com 
cartes.netscape.ca 
celebrity.aol.co.uk 
celestrellas.com 
channel-02.aol.co.jp 
channel.aol.co.jp 
chile.aol.com 
chinese.autoblog.com 
cine.aol.es 
cinematical.com 
cinematical.es 
citysbest.com
client.winamp.com 
cn.aol.com 
cn.autoblog.com 
colombia.aol.com 
comedy.aol.com 
comicsalliance.com 
compaq-desktop.aol.com 
compaq-laptop.aol.com 
content.aol.co.jp 
content.living.aol.com 
conversations.blackvoices.com 
create-2.love.com 
cssvc.travel.compuserve.com 
dailyfinance.co.uk 
dailyfinance.com 
daol.aol.com 
de.autoblog.com 
de.shoutcast.com 
deportes.aol.com 
diets.aol.com 
digitalphotography.weblogsinc.com 
dinero.aol.com 
divester.com 
diylife.com 
downloadsquad.com 
dynamic.aol.com 
eleven.aol.co.uk 
ellen.aol.com 
emurse.com 
engadget.com (not aol.it encoded but stil counts in contest)
entertainment.aol.com 
es.autoblog.com 
es.spinner.com 
estilodiario.com 
fanaticos.com 
fanhouse.com 
fantasy.fanhouse.com 
fantasybaseball.fanhouse.com 
fantasybasketball.fanhouse.com 
fantasyfootball.fanhouse.com 
feedback.blackvoices.com 
feeds.news.aol.com 
film.aol.co.uk 
film.aol.nl 
finance.aol.com 
fleaflicker.com 
flytrapgames.com 
food.aol.com 
football.fanhouse.co.uk 
forums.winamp.com 
fr.aol.ca 
fr.asylum.com 
fr.autoblog.com 
gadling.com 
gamedaily.com 
games.aol.com 
games.com 
gamesdotcom.aol.com 
gayandlesbian.aol.com 
gnn.com 
golf.fanhouse.com 
green.autoblog.com 
greendaily.com 
health.aol.com 
health.parentdish.com 
hiqvideo.aol.com 
holidash.com 
home.aol.com 
horoscopes.aol.com 
horrorsquad.com 
hot.aol.com 
house.aol.jp 
housingwatch.com 
hp-consumer.aol.my 
hp-desktop.aol.com 
hp-laptop.aol.com 
i.love.com 
in-store.com 
insideaolvideo.com 
insidemovies.moviefone.com 
insidetv.aol.com 
insurance.blackvoices.com 
intimos.com 
intl.shoutcast.com 
jay-mariotti.fanhouse.com 
jobs.aol.com 
joystiq.com 
jp.aol.com 
jp.autoblog.com 
jp.joystiq.com 
jp.luxist.com 
jsyk.com 
juegos.aol.com 
kevin-blackistone.fanhouse.com 
kids.aol.com 
kino.aol.pl 
kitchendaily.co.uk 
kitchendaily.com 
kol.com 
latent.channel.aol.com 
latino.aol.com 
lemon-drop.com.au 
lemondrop.co.uk 
lemondrop.com 
lerhu.com 
lisa-olson.fanhouse.com 
living.aol.co.uk 
living.aol.com 
love.com 
luxist.com 
main.welcomescreen.aol.com 
massively.com 
media.gamedaily.com 
member.aol.co.jp 
mlb.fanhouse.com 
mma.fanhouse.com 
mmafighting.com 
mobile.aol.co.jp 
mobile.aol.com 
mobile1.aol.com 
money.aol.co.jp 
money.aol.com 
motorsports.fanhouse.com 
moviefone.ca 
moviefone.co.uk 
moviefone.com 
movies.aol.com 
movies.channel.aol.com 
music.aol.com 
musica.aol.com 
my.netscape.com 
mydaily.com 
nascar.fanhouse.com 
nba.fanhouse.com 
ncaabasketball.fanhouse.com 
ncaafootball.fanhouse.com 
ncaatournament.fanhouse.com 
netcenter.netscape.com 
netscape.aol.ca 
netscape.ca 
netscape.com 
netscape.fr 
netscape.qc.ca 
network.aol.com 
news.aol.ca 
news.aol.co.uk 
news.aol.com 
news.aol.com.aol.akadns.net 
news.bigdownload.com 
news.holidash.com 
news.mydaily.com 
news.travel.aol.com 
newsblog.aol.in 
newsrunner.com 
nfl.fanhouse.com 
nhl.fanhouse.com 
nintendo.joystiq.com 
noisecreep.com 
noticias.aol.com 
olympics.fanhouse.com 
origin.celebrite.aol.fr 
outdoors.fanhouse.com 
owl.com 
parentdish.co.uk 
parentdish.com 
parentdishblog.ca 
pawnation.com 
personals.aol.com 
pets.aol.com 
pf.channel.aol.com 
photos.popeater.com 
pixcetera.co.uk 
pixcetera.com 
pixcetera.jp 
pl.spinner.com 
playsavvy.com 
playstation.joystiq.com 
politicsdaily.co.uk 
politicsdaily.com 
popeater-preview.aol.fr 
popeater.ca 
popeater.cms.aol.fr 
popeater.com 
popeater.fr 
popeater.origin.aol.fr 
portail.dartybox.com 
portal.estage.aol.com 
propeller.com 
queersighted.co.uk 
queersighted.com 
radaol-prod-web-rr.streamops.aol.com 
realestate.aol.com 
realestate.staging.aol.com 
recipe.aol.com 
rentedspaces.com 
rubyroom.aol.co.uk 
salud.aol.com 
scifisquad.com 
search.blackvoices.aol.com 
secondlifeinsider.com 
services.winamp.com 
shelterpop.com 
shopping.aol.com 
shoutcast.com 
shoutcastblog.com 
singingfish.com 
site.aol.com 
slashcontrol.com 
slashfood.com 
smallbusiness.aol.com 
soccer.fanhouse.com 
sphere.com 
spinner.ca 
spinner.com 
spinnermusic.co.uk 
sport.aol.co.uk 
sports.aol.com 
stage.dailyfinance.com 
stage.uk.aol.com 
staging.shopping.aol.com 
startpage.aol.com 
stg.uk.aol.com 
streampad.com 
streetlevel.com 
style.aol.com 
stylelist.com 
stylelist.comblog 
superbowl.fanhouse.com 
superbowlads.fanhouse.com 
svc.travel.aol.co.uk 
switched.com 
t.aol.com 
techcrunch.com (not aol.it encoded but stil counts in contest)
tecnologia.aol.es 
tecnopadres.com 
television.aol.com 
tennis.fanhouse.com 
thatsfit.ca 
thatsfit.co.uk 
thatsfit.com 
theboombox.com 
theboot.com 
thecancerblog.com 
thediabetesblog.com 
theinsider.tripvine.com 
toshiba.aol.ca 
tourtracker.com 
translogic.aolautos.com 
travel.aol.co.uk 
travel.aol.com 
travel.compuserve.co.uk 
travel.netscape.co.uk 
tuaw.com 
tugente.aol.com 
tunome.com 
tuvida.aol.com 
tuvidaymas.com 
tuvotoestufuturo.com 
tuvozentuvida.com 
tv.aol.co.uk 
tvlistings.aol.com 
tvsquad.com 
uk.autoblog.com 
uk.games.com 
uk.sylelist.com 
upp.asylum.com 
upp.www.asylum.com 
urlesque.com 
venezuela.aol.com 
veo-novelas.com 
video.aimtoday.com 
video.aol.ca 
video.aol.co.uk 
video.aol.com 
video.aol.in 
video.aol.jp 
videogames.aol.com 
videoqa.test.aol.com 
walletpop.co.uk 
walletpop.com 
walletpop.de 
weather.aol.co.uk 
weather.aol.com 
web.travel.aol.co.uk 
webcenter.travel.aol.com 
webcenter.travel.netscape.com 
webcenters.netscape.com 
weblogsinc.com 
wechoosethemoon.org 
welcomescreen.aolsvc.co.uk 
whereitsat.com 
winamp.com 
wow.com 
www-stg.uk.aol.com 
www.africana.com 
www.aisledash.com 
www.alice.aol.de 
www.aol.ca 
www.aol.co.jp 
www.aol.co.uk 
www.aol.com 
www.aol.com.hk 
www.aol.com.pr 
www.aol.cricket20.com 
www.aol.de 
www.aol.fr 
www.aol.jp 
www.aol.qc.ca 
www.aolbollywood.com 
www.aolbroadband.welcomescreen.aol.co.uk 
www.aolcommunity.aol.co.jp 
www.aolhealth.com 
www.aollatinoblog.com 
www.aolmobile.aol.com 
www.aolnews.com 
www.aolracing.com 
www.aolradioblog.com 
www.aolsvc.latino.stats.aol.com 
www.aolsvc.mercurytivo.aol.com 
www.aolsvc.news.aol.com 
www.aolsvc.pf.aol.com 
www.aolsvc.travel.survey.aol.com 
www.aolsvc.weather.aol.com 
www.aoltv.ca 
www.aoltv.co.uk 
www.aoltvlistings.compuserve.com 
www.aoltvlistings.cssvc.com 
www.aoltvlistings.netscape.com 
www.aolvideoblog.com 
www.archive.blackvoices.com 
www.argentina.aol.com 
www.asylum.co.uk 
www.asylum.com 
www.asylum.com.au 
www.asylum.in 
www.asylum.jp 
www.asylumitalia.it 
www.auto-insurance.blackvoices.com 
www.autoblog.com 
www.automoviles.aol.com 
www.autos.aol.com 
www.autos.blackvoices.com 
www.backporch.fanhouse.com 
www.beta.gamedaily.com 
www.blackvoices.aol.com 
www.blackvoices.com 
www.blog.emurse.com 
www.blog.games.com 
www.blog.propeller.com 
www.blog.winamp.com 
www.bloggingbuyouts.com 
www.bloggingneworleans.com 
www.bloggingstocks.com 
www.bloggingsundance.com 
www.blogs.blackvoices.com 
www.bollywoodblog.aol.in 
www.books.aol.com 
www.boxing.fanhouse.com 
www.broadband.aol.co.uk 
www.buenos-padres.com 
www.buscadorlatino.aol.com 
www.bvblackspin.com 
www.bvbuzz.com 
www.bvhairtalk.com 
www.bvnewswire.com 
www.bvonbooks.com 
www.bvonlove.com 
www.bvonmoney.com 
www.bvonmovies.com 
www.bvonsports.com 
www.bvonstyle.com 
www.bvwellness.com 
www.cambio.com 
www.canada.aol.com 
www.careerhelp.emurse.com 
www.cartes.netscape.ca 
www.celebrity.aol.co.uk 
www.celestrellas.com 
www.channel-02.aol.co.jp 
www.channel.aol.co.jp 
www.chile.aol.com 
www.chinese.autoblog.com 
www.cine.aol.es 
www.cinematical.com 
www.cinematical.es 
www.client.winamp.com 
www.cn.aol.com 
www.cn.autoblog.com 
www.colombia.aol.com 
www.comedy.aol.com 
www.comicsalliance.com 
www.compaq-desktop.aol.com 
www.compaq-laptop.aol.com 
www.content.aol.co.jp 
www.content.living.aol.com 
www.conversations.blackvoices.com 
www.create-2.love.com 
www.cssvc.travel.compuserve.com 
www.dailyfinance.co.uk 
www.dailyfinance.com 
www.daol.aol.com 
www.de.autoblog.com 
www.de.shoutcast.com 
www.deportes.aol.com 
www.diets.aol.com 
www.digitalphotography.weblogsinc.com 
www.dinero.aol.com 
www.divester.com 
www.diylife.com 
www.downloadsquad.com 
www.dynamic.aol.com 
www.eleven.aol.co.uk 
www.ellen.aol.com 
www.emurse.com 
www.entertainment.aol.com 
www.es.autoblog.com 
www.es.spinner.com 
www.estilodiario.com 
www.fanaticos.com 
www.fanhouse.com 
www.fantasy.fanhouse.com 
www.fantasybaseball.fanhouse.com 
www.fantasybasketball.fanhouse.com 
www.fantasyfootball.fanhouse.com 
www.feedback.blackvoices.com 
www.feeds.news.aol.com 
www.film.aol.co.uk 
www.film.aol.nl 
www.finance.aol.com 
www.fleaflicker.com 
www.flytrapgames.com 
www.food.aol.com 
www.football.fanhouse.co.uk 
www.forums.winamp.com 
www.fr.aol.ca 
www.fr.asylum.com 
www.fr.autoblog.com 
www.gadling.com 
www.gamedaily.com 
www.games.aol.com 
www.games.com 
www.gamesdotcom.aol.com 
www.gayandlesbian.aol.com 
www.gnn.com 
www.golf.fanhouse.com 
www.green.autoblog.com 
www.greendaily.com 
www.health.aol.com 
www.health.parentdish.com 
www.hiqvideo.aol.com 
www.holidash.com 
www.home.aol.com 
www.horoscopes.aol.com 
www.horrorsquad.com 
www.hot.aol.com 
www.house.aol.jp 
www.housingwatch.com 
www.hp-consumer.aol.my 
www.hp-desktop.aol.com 
www.hp-laptop.aol.com 
www.i.love.com 
www.in-store.com 
www.insideaolvideo.com 
www.insidemovies.moviefone.com 
www.insidetv.aol.com 
www.insurance.blackvoices.com 
www.intimos.com 
www.intl.shoutcast.com 
www.jay-mariotti.fanhouse.com 
www.jobs.aol.com 
www.joystiq.com 
www.jp.aol.com 
www.jp.autoblog.com 
www.jp.joystiq.com 
www.jp.luxist.com 
www.jsyk.com 
www.juegos.aol.com 
www.kevin-blackistone.fanhouse.com 
www.kids.aol.com 
www.kino.aol.pl 
www.kitchendaily.co.uk 
www.kitchendaily.com 
www.kol.com 
www.latent.channel.aol.com 
www.latino.aol.com 
www.lemon-drop.com.au 
www.lemondrop.co.uk 
www.lemondrop.com 
www.lerhu.com 
www.lisa-olson.fanhouse.com 
www.living.aol.co.uk 
www.living.aol.com 
www.love.com 
www.luxist.com 
www.main.welcomescreen.aol.com 
www.massively.com 
www.media.gamedaily.com 
www.member.aol.co.jp 
www.mlb.fanhouse.com 
www.mma.fanhouse.com 
www.mmafighting.com 
www.mobile.aol.co.jp 
www.mobile.aol.com 
www.mobile1.aol.com 
www.money.aol.co.jp 
www.money.aol.com 
www.motorsports.fanhouse.com 
www.moviefone.ca 
www.moviefone.co.uk 
www.moviefone.com 
www.movies.aol.com 
www.movies.channel.aol.com 
www.music.aol.com 
www.musica.aol.com 
www.my.netscape.com 
www.mydaily.com 
www.nascar.fanhouse.com 
www.nba.fanhouse.com 
www.ncaabasketball.fanhouse.com 
www.ncaafootball.fanhouse.com 
www.ncaatournament.fanhouse.com 
www.netcenter.netscape.com 
www.netscape.aol.ca 
www.netscape.ca 
www.netscape.com 
www.netscape.fr 
www.netscape.qc.ca 
www.network.aol.com 
www.news.aol.ca 
www.news.aol.co.uk 
www.news.aol.com 
www.news.aol.com.aol.akadns.net 
www.news.bigdownload.com 
www.news.holidash.com 
www.news.mydaily.com 
www.news.travel.aol.com 
www.newsblog.aol.in 
www.newsrunner.com 
www.nfl.fanhouse.com 
www.nhl.fanhouse.com 
www.nintendo.joystiq.com 
www.noisecreep.com 
www.noticias.aol.com 
www.olympics.fanhouse.com 
www.origin.celebrite.aol.fr 
www.outdoors.fanhouse.com 
www.owl.com 
www.parentdish.co.uk 
www.parentdish.com 
www.parentdishblog.ca 
www.pawnation.com 
www.personals.aol.com 
www.pets.aol.com 
www.pf.channel.aol.com 
www.photos.popeater.com 
www.pixcetera.co.uk 
www.pixcetera.com 
www.pixcetera.jp 
www.pl.spinner.com 
www.playsavvy.com 
www.playstation.joystiq.com 
www.politicsdaily.co.uk 
www.politicsdaily.com 
www.popeater-preview.aol.fr 
www.popeater.ca 
www.popeater.cms.aol.fr 
www.popeater.com 
www.popeater.fr 
www.popeater.origin.aol.fr 
www.portail.dartybox.com 
www.portal.estage.aol.com 
www.propeller.com 
www.queersighted.co.uk 
www.queersighted.com 
www.radaol-prod-web-rr.streamops.aol.com 
www.realestate.aol.com 
www.realestate.staging.aol.com 
www.recipe.aol.com 
www.rentedspaces.com 
www.rubyroom.aol.co.uk 
www.salud.aol.com 
www.scifisquad.com 
www.search.blackvoices.aol.com 
www.secondlifeinsider.com 
www.services.winamp.com 
www.shelterpop.com 
www.shopping.aol.com 
www.shoutcast.com 
www.shoutcastblog.com 
www.singingfish.com 
www.site.aol.com 
www.slashcontrol.com 
www.slashfood.com 
www.smallbusiness.aol.com 
www.soccer.fanhouse.com 
www.sphere.com 
www.spinner.ca 
www.spinner.com 
www.spinnermusic.co.uk 
www.sport.aol.co.uk 
www.sports.aol.com 
www.stage.dailyfinance.com 
www.stage.uk.aol.com 
www.staging.shopping.aol.com 
www.startpage.aol.com 
www.stg.uk.aol.com 
www.streampad.com 
www.streetlevel.com 
www.style.aol.com 
www.stylelist.com 
www.stylelist.comblog 
www.superbowl.fanhouse.com 
www.superbowlads.fanhouse.com 
www.svc.travel.aol.co.uk 
www.switched.com 
www.t.aol.com 
www.tecnologia.aol.es 
www.tecnopadres.com 
www.television.aol.com 
www.tennis.fanhouse.com 
www.thatsfit.ca 
www.thatsfit.co.uk 
www.thatsfit.com 
www.theboombox.com 
www.theboot.com 
www.thecancerblog.com 
www.thediabetesblog.com 
www.theinsider.tripvine.com 
www.toshiba.aol.ca 
www.tourtracker.com 
www.translogic.aolautos.com 
www.travel.aol.co.uk 
www.travel.aol.com 
www.travel.compuserve.co.uk 
www.travel.netscape.co.uk 
www.tuaw.com 
www.tugente.aol.com 
www.tunome.com 
www.tuvida.aol.com 
www.tuvidaymas.com 
www.tuvotoestufuturo.com 
www.tuvozentuvida.com 
www.tv.aol.co.uk 
www.tvlistings.aol.com 
www.tvsquad.com 
www.uk.autoblog.com 
www.uk.games.com 
www.uk.sylelist.com 
www.upp.www.asylum.com 
www.urlesque.com 
www.venezuela.aol.com 
www.veo-novelas.com 
www.video.aimtoday.com 
www.video.aol.ca 
www.video.aol.co.uk 
www.video.aol.com 
www.video.aol.in 
www.video.aol.jp 
www.videogames.aol.com 
www.videoqa.test.aol.com 
www.walletpop.co.uk 
www.walletpop.com 
www.walletpop.de 
www.weather.aol.co.uk 
www.weather.aol.com 
www.web.travel.aol.co.uk 
www.webcenter.travel.aol.com 
www.webcenter.travel.netscape.com 
www.webcenters.netscape.com 
www.weblogsinc.com 
www.wechoosethemoon.org 
www.welcomescreen.aolsvc.co.uk 
www.whereitsat.com 
www.winamp.com 
www.wow.com 
www.xbox.joystiq.com 
www.zones.aim.com 
xbox.joystiq.com 
zones.aim.com 
</pre> 
	</div>

	</div>
   <div id="ft"><p></p></div>
</div>
</body>
</html>

</div>

</body>